FROM openjdk:22-slim-bullseye
WORKDIR /app/wildfly
COPY . .
RUN apt update && apt upgrade -y
RUN apt install wget -y
RUN wget https://github.com/wildfly/wildfly/releases/download/30.0.0.Final/wildfly-30.0.0.Final.tar.gz
RUN tar -xvf wildfly-30.0.0.Final.tar.gz
RUN wget https://dlcdn.apache.org/maven/maven-3/3.9.5/binaries/apache-maven-3.9.5-bin.tar.gz
RUN tar -xvf apache-maven-3.9.5-bin.tar.gz
RUN apt install git -y
EXPOSE 8080
ENTRYPOINT ["entrypoint.sh"]